project:
  type: website
  output-dir: docs

website:
  title: "mrkznrns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datastory.qmd
        text: Singapore's Public Housing Affordability

format:
  html:
    shiny: true
    theme:   
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
