project:
  type: website
  output-dir: docs

website:
  title: "mrkznrns.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: articles.qmd
        text: Personal Research and Articles
      - href: interests.qmd
        text: My Interests
        


format:
  html:
    shiny: true
    theme: journal
    css: styles.css
    toc: true

editor: visual
