---
title: "My Past Work"
---

```{r, eval=TRUE,echo=FALSE}
```

<br> I've dabbled in UX/UI design and video editing, mostly picking up these skills on my own because I'm really into it. I love creating cool user experiences and videos that pop, and I'm excited to keep leveling up and bringing more creativity to my work!

# Video Editing and Production Work

## Nature Versus Nurture - Podcast Debate in Animation Style

For this project, I focused on experimenting with animation and editing techniques to create a visually engaging, debate-style segment on the topic of transgender athletes in competitive sports. I used Canva for design elements, CapCut for assembling motion sequences, and Final Cut Pro for final compositing and audio syncing.

This was a creative testbed where I explored how layered visuals and stylized transitions could enhance both the clarity and emotional tone of the arguments presented---turning complex social commentary into an accessible and compelling visual narrative.

{{< video https://www.youtube.com/embed/n0J641t6IUE?si=qjfJfLo7WTwzktS1 >}}

## Savvify - An Automated Savings Platform

During my time in Temasek Polytechnic, my group mates and I worked on an automated savings platform - ***Savvify***. Essentially, the application helps users to round up your payment transactions to the nearest dollar, and crediting it to the users' e-wallet upon making QR Payments.

Our main goal was to bring new solutions e-payment solutions while helping young adults like us, to understand real life responsibilities - improving their financial literacy!

{{< video https://youtu.be/kzWq31_mRyc >}}

## Digital Storytelling

#### Pattoo Tarlour: The Art of the Needle

Here, we interviewed Pattoo Tarlour, a local tattoo business. We explored the artistry, passion, and personal stories behind tattooing in Singapore.

Through interviews with talented artists, visuals of their creative process, and dynamic shots capturing the parlour's ambiance, the documentary highlights the unique culture and meaningful connections that define the space. It celebrates the cultural and artistic significance of tattooing as both a craft and an expression of identity.

{{< video https://www.youtube.com/embed/AoD6FvMuHxk?si=t2d06a4Opw8NPRXV >}}

#### Day in the Life: Captured Through Film

During a casual cycling session, Marzuki (me) finds himself in an unusual situation -- discovering a photo album and film camera left behind. He takes the opportunity to slow down and capture moments from the day in the lives of everyday people while enjoying his ride.

{{< video https://www.youtube.com/embed/Nz8UhdKpz-Y?si=FymUgJAb4lcMtJB9 >}}

## Social Thought and Theory

In this module, we explored the contributions of the founding fathers of Sociology - Marx, Weber and Durkheim. This Social Media assignment looks into Weber's ideas found in the The Protestant Work Ethic and the Spirit of Capitalism and Bureaucracy.

Here, we discussed (in a very Gen-Z way) that we have to be (economically) productive every single minute of our day, how we should be "growing money even in our sleep" is increasingly prevalent today. How everything we do now is to be justified in economic terms and we end up losing meaning, becoming disenchanted in life - Here's what we did!

{{< video https://www.youtube.com/embed/-SYPjaJoi-I?si=ViXbIgq6TR4Lmbh4 >}}

<a href="https://www.canva.com/design/DAF0lbgxhPk/jKGt5Uqtio2trLaLP-h9tw/view?utm_content=DAF0lbgxhPk&utm_campaign=designshare&utm_medium=embeds&utm_source=link" target="_blank" rel="noopener"> </a>

## GIGAWipes - Innovation through Programming

"Innovation does not stop" -- Here, we explored how to incorporate programming in our daily lives. This may or may not be inspired by true events but for this project, we created a prototype of a toilet roll dispenser but... I'll let the video do the talking...

{{< video https://youtu.be/2yBwaRCfiuI >}}

Not bad aye! Essentially, The lanyard communicates via Bluetooth. this ensures that toilet rolls are filled and readily available for use, maintaining hygiene and convenience in restrooms

```         
```

```         
```
